<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Bootstrap Dictionary Plugin
    |--------------------------------------------------------------------------
    |
    | Whether to show the Dictionary plugin. Defaults to false in production.
    | Set this to true if you want to enable code generation in production,
    | though it's recommended to keep this disabled for security reasons.
    |
    | Environment Variable: DICTIONARY_SHOW
    |
    */
    'show' => env('DICTIONARY_SHOW', ! app()->isProduction()),

    /*
    |--------------------------------------------------------------------------
    | Default Generation Options
    |--------------------------------------------------------------------------
    |
    | Configure which files should be generated by default when creating a new
    | resource through the Dictionary wizard. These defaults can be overridden
    | per-resource in the wizard interface.
    |
    | Note: Migrations are always generated as they are core to the plugin.
    |
    | - generate_factory: Create model factory for testing and seeding
    | - generate_seeder: Create database seeder class
    | - generate_resource: Create complete Filament resource with CRUD pages
    |
    */
    'generate_factory' => env('DICTIONARY_GENERATE_FACTORY', true),
    'generate_seeder' => env('DICTIONARY_GENERATE_SEEDER', true),
    'generate_resource' => env('DICTIONARY_GENERATE_RESOURCE', true),

    /*
    |--------------------------------------------------------------------------
    | Default Generation Mode
    |--------------------------------------------------------------------------
    |
    | Controls how Dictionary should behave when target artifacts already exist.
    |
    | - create: only create missing files and skip existing artifacts
    | - merge: update managed/generated parts without replacing the whole file
    | - replace: rewrite generated artifacts and allow destructive workflows
    |
    */
    'default_generation_mode' => env('DICTIONARY_DEFAULT_GENERATION_MODE', 'merge'),

    /*
    |--------------------------------------------------------------------------
    | Generated File Formatting
    |--------------------------------------------------------------------------
    |
    | When enabled, Dictionary will try to run a formatter after writing or
    | updating generated PHP files so merged code remains readable.
    |
    | Supported formatter values:
    | - pint_if_available: run Pint only when a local binary exists
    | - pint: require Pint to exist locally, otherwise skip silently
    | - none: disable formatter execution entirely
    |
    */
    'format_generated_files' => env('DICTIONARY_FORMAT_GENERATED_FILES', true),
    'formatter' => env('DICTIONARY_FORMATTER', 'pint_if_available'),

    /*
    |--------------------------------------------------------------------------
    | Models Namespace
    |--------------------------------------------------------------------------
    |
    | The default namespace for generated Eloquent models. This determines
    | where your model classes will be created when using the Dictionary wizard.
    |
    */
    'models_namespace' => env('DICTIONARY_MODELS_NAMESPACE', env('DICTIONARY_NAMESPACE', 'App\\Models')),
    'namespace' => env('DICTIONARY_NAMESPACE', env('DICTIONARY_MODELS_NAMESPACE', 'App\\Models')),

    /*
    |--------------------------------------------------------------------------
    | Factories Namespace
    |--------------------------------------------------------------------------
    |
    | The default namespace for generated model factories. This determines
    | where your factory classes will be created for testing and seeding.
    |
    */
    'factories_namespace' => env('DICTIONARY_FACTORIES_NAMESPACE', 'Database\\Factories'),

    /*
    |--------------------------------------------------------------------------
    | Seeders Namespace
    |--------------------------------------------------------------------------
    |
    | The default namespace for generated database seeders. This determines
    | where your seeder classes will be created for populating test data.
    |
    */
    'seeders_namespace' => env('DICTIONARY_SEEDERS_NAMESPACE', 'Database\\Seeders'),
    'seeder_namespace' => env('DICTIONARY_SEEDERS_NAMESPACE', 'Database\\Seeders'),

    /*
    |--------------------------------------------------------------------------
    | Filament Resources Namespace
    |--------------------------------------------------------------------------
    |
    | The default namespace for generated Filament resources. This determines
    | where your resource classes (including pages and actions) will be created.
    |
    */
    'resources_namespace' => env('DICTIONARY_RESOURCES_NAMESPACE', 'App\\Filament\\Resources'),

    /*
    |--------------------------------------------------------------------------
    | Filament Resource Structure Version
    |--------------------------------------------------------------------------
    |
    | Controls the folder structure and file layout used when generating
    | Filament resources. Choose based on your installed Filament version.
    |
    | - 'v3': monolithic structure — form, infolist and table are defined
    |         inline inside a single UserResource.php file; pages live in
    |         a UserResource/Pages/ sub-folder.
    |
    | - 'v4': domain-based structure — each concern is extracted to its own
    |         class (UserForm, UserInfolist, UsersTable) inside dedicated
    |         Schemas/ and Tables/ sub-folders; everything lives under a
    |         per-model domain folder (e.g. Resources/Users/).
    |
    | Environment Variable: DICTIONARY_FILAMENT_VERSION
    |
    */
    'filament_version' => env('DICTIONARY_FILAMENT_VERSION', 'v4'),

];
